### ISSUE TITLE
Submarine Animation Using HTML & CSS

### ISSUE THREAD

**Issue by Robinrai2612** [Durgesh4993/web_Animation#27]
## Animation Name
Subamarine Animation 

## Description

pure-css, searching, animation, dribbble, codevember

## Task

- [x] Connect Us On social media -
- [x]      <a href="https://github.com/Durgesh4993" target="_blank">GitHub</a>
- [x]      <a href="https://www.linkedin.com/in/durgesh4993/" target="_blank">LinkedIn</a>
- [x]     <a href="https://www.youtube.com/channel/UCRFVEkJLCknREaO40evl1uQ" target="_blank">YouTube</a>

**Comment by ZainabR11** [comment]
Okay
