### ISSUE TITLE
Liquid Drop Login Page Animation

### ISSUE THREAD

**Issue by Robinrai2612** [Durgesh4993/web_Animation#42]
## Animation Name

Liquid Drop Login Page Animation

## Description

The Liquid Drop Login Page Animation is a visually captivating and dynamic user interface design created using a combination of HTML and CSS. This login page animation aims to provide a unique and engaging experience for users as they access a web application or website. The animation's central theme revolves around fluidity, with elements resembling liquid drops moving and transforming to guide the user through the login process.

## Task

- [x] Connect Us On social media -
- [x]      <a href="https://github.com/Durgesh4993" target="_blank">GitHub</a>
- [x]      <a href="https://www.linkedin.com/in/durgesh4993/" target="_blank">LinkedIn</a>
- [x]     <a href="https://www.youtube.com/channel/UCRFVEkJLCknREaO40evl1uQ" target="_blank">YouTube</a>

@Durgesh4993 I would like to work on this issue. Kindly assign it to me.

**Comment by real-coder007Ravi** [comment]
@Durgesh4993 Could u please assign it to me

**Comment by Robinrai2612** [comment]
@real-coder007Ravi Sorry Buddy I am already working on it. I f you want you can create an issue and start working on it and ask @Durgesh4993 to assign you that issue.

**Comment by real-coder007Ravi** [comment]
No problem, @Robinrai2612.
Please continue, I will try to create another issue and work on it.

**Comment by Robinrai2612** [comment]
@real-coder007Ravi Yes
